### ISSUE TITLE
removeSentenceListener, by type improvement?

### ISSUE THREAD

**Issue by handyli** [ktuukkan/marine-api#101]
Hi,
There is addSentenceListener(SentenceListener sl, String type).
Would it make sense to have possibility to remove listener by type? Now only option is:
removeSentenceListener(SentenceListener listener)

I have one listener (tcp port) which I want to receive only some sentences and to be able to change sentences later. Current removeSentenceListener will remove all SentenceListeners.

I have GPS feed coming from serial port. After connection to tcp port for example RMC and GSA would initially sent to tcp client. Client would be able to add or remove sentences it receives. Add works fine, but remove will remove all sentences. Workaround would be to remove all listeners and then to add again those which are still wanted. 

I'm currently using snaphot-0.11.

**Comment by ktuukkan** [comment]
Yes, the current implementation removes the listener regardless of types it was added for, so I understand it may be a problem if you've registered the same listener for many types. The suggestion seems feasible and easy to implement, so I don't see problems in adding it.

**Comment by ktuukkan** [comment]
@handyli, this is now done in the latest snapshot.
