### ISSUE TITLE
TTM Sentence Parser doesn't have Getters for course (T/R) and bearing (T/R)

### ISSUE THREAD

**Issue by NontasPantzopoulos** [ktuukkan/marine-api#108]
`src/main/java/net/sf/marineapi/nmea/parser/TTMParser.java`

I believe there should be getters for BEARING_TRUE_REL and COURSE_TRUE_REL, because it depends on RADAR device settings. FYI, it is not always T (TRUE). Some older devices transmit NMEA messages with these two values set to R (RELATIVE). If you add this change, a programmer could write some logic to it, in order to catch all the cases.

**Comment by ktuukkan** [comment]
Hi! Thanks for pointing out, these are very easy to add.

**Comment by ktuukkan** [comment]
Resolved in #112
