### ISSUE TITLE
Unable to register own parser to a reader

### ISSUE THREAD

**Issue by SashLi** [ktuukkan/marine-api#111]
Hi, first thank you for your very nice work here.
I implemented to own parser for "$PFLAU" and want to register this parser to a SentenceReader that is listening on a serial port.

I could not found a hook to register the parser.

Always returns a "WARNING: Parser for type 'FLAU' not found"

Its an instance fo the SentenceReader 

`SentenceReader reader = new SentenceReader(port.getInputStream());
 reader.addSentenceListener(new MultiSentenceListener(appController));
reader.start();`

**Comment by ktuukkan** [comment]
Hi, sorry for the late reply, it seems I'm not getting any notifications from this project for some reason.

You may add your own parsers in the [SentenceFactory](https://www.javadoc.io/doc/net.sf.marineapi/marineapi/latest/net/sf/marineapi/nmea/parser/SentenceFactory.html), see the `registerParser()` method. After that, you use the reader just like before, adding only the listerners in there.
