### ISSUE TITLE
ais.util.ShipType - CargoType?

### ISSUE THREAD

**Issue by joshsweaney** [ktuukkan/marine-api#117]
The ShipType util class for AIS combines the cargo type and the ship type into a single string. There is no method to get the cargo type string, and the String array of second digit (cargo digit) codes is private. It is common to display the two fields separately on navigational displays.

It would be helpful if there were separate methods for getting the ship type string and cargo type string.

**Comment by ktuukkan** [comment]
Thanks for reporting, I'll have a look on this after my vacation.
