### ISSUE TITLE
Make AIS length validation less restricted

### ISSUE THREAD

**Issue by qtran** [ktuukkan/marine-api#121]
Hi,
would it be possible to make the AIS length validation less restricted or configurable?
Due to tests with different AIS sources we noticed that sometimes that it is required to increase the maximum length.

Best regards

**Comment by ktuukkan** [comment]
Hi @qtran, could you give some examples cases?

**Comment by RiseOfDeath** [comment]
Seems that it hardcoded: As example in AISPositionReportParser.java:
`		if (content.length() != 168)
			throw new IllegalArgumentException("Wrong message length");`

**Comment by ktuukkan** [comment]
Please provide more context and sample data - or preferrably a pull-request proposing a fix.

**Comment by ktuukkan** [comment]
As far as I see, the length is according to spec and arbitrary length would heavily affect payload decoding - e.g. which field(s) should be affected by the added or removed bits? - so I believe the root problem is in your data not respecting the spec. Hence, I don't see any feasible changes to be made, but feel free to propose any improvements you may have.
