### ISSUE TITLE
FaaMode does not support RTK

### ISSUE THREAD

**Issue by svnhub** [ktuukkan/marine-api#128]
Some of the new receivers can send new modes that are not part of the FaaMode enum:

These already exist in marine-api:
A=Autonomous
M=Manual input
D=Differential
E=Estimated
P=Precise
N=No fix
S=Simulator

These real time kinematic modes are missing:
R=RTK fixed 
F=RTK float

**Comment by ktuukkan** [comment]
Thanks, I'll add them in the enum :+1:

**Comment by ktuukkan** [comment]
Added the modes and deployed in snapshot.
