### ISSUE TITLE
Android Proguard issue with marine-api

### ISSUE THREAD

**Issue by eclectice** [ktuukkan/marine-api#130]
Just a reminder that if this API is used in an Android project and the `minifyEnabled true` option is used, the following proguard entry must be added:
```lang-proguard
-keep class net.sf.marineapi.** { *; }
-dontwarn gnu.io.CommPortIdentifier
-dontwarn gnu.io.RXTXPort
-dontwarn gnu.io.SerialPort
```

**Comment by ktuukkan** [comment]
Hi @eclectice, thanks! I'm not familiar with Android, is there anything that could be done on the library to avoid that?

**Comment by eclectice** [comment]
It is highly specialized to Android development, where Android developers can use the Proguard functionality to minimize, optimize, and obfuscate the Java/Kotlin codes...I guess it can be included in the README or Wiki. 

The final Proguard setting that I use right now is:

```lang-proguard
-keep class net.sf.marineapi.** { *; }
-keep interface net.sf.marineapi.** { *; }
-keepattributes MethodParameters
-dontwarn gnu.io.CommPortIdentifier
-dontwarn gnu.io.RXTXPort
-dontwarn gnu.io.SerialPort
```

The marine-api calls are not executed at all if the Proguard configuration is not included in the Android app's `build.gradle` script file.

**Comment by ktuukkan** [comment]
Updated README with this info, thanks!
