### ISSUE TITLE
Encoding AIVDM with fragments 

### ISSUE THREAD

**Issue by mikeshedrack** [ktuukkan/marine-api#135]
// !AIVDM,2,1,0,A,58wt8Ui`g??r21`7S=:22058<v05Htp000000015>8OA;0sk,0*7B
    // !AIVDM,2,2,0,A,eQ8823mDm3kP00000000000,2*5D
   
How can i be able to encode  above nmea sentences

**Comment by ktuukkan** [comment]
You may use [AISMessageFactory](https://www.javadoc.io/static/net.sf.marineapi/marineapi/0.11.0/net/sf/marineapi/ais/parser/AISMessageFactory.html) to _decode_ AIS messages, but this library does not encode them.
