### ISSUE TITLE
RMCParser Error

### ISSUE THREAD

**Issue by lexxel** [ktuukkan/marine-api#18]
I have a GPS device which delivers an empty field for "speed" when it never was moved.
This leads to the RMC sentence being unparsable because a DataNotAvailableException is thrown in SentenceParser.java method getStringValue().

A quick fix would be to catch the exception in SentenceParser.getDoubleValue() and set the value to 0.

Thanks and kind regards,
Alex

**Comment by ktuukkan** [comment]
This is rather device-specific issue and also not so easily fixed because not all values have feasible defaults. Also, using null doesn't feel like a good idea because it cannot be assigned to primitive types.

**Comment by lexxel** [comment]
Thats a pitty ... It makes the API unusable for me.
In my opinion it would be best to use only non-primitive data types. This would allow you to return null in any case a device does not deliver what it should (or what the standard says).
This would make the API much more usable and would allow the developer to react better on his specific device (by checking the values for null value where needed and react accordingly).

**Comment by ktuukkan** [comment]
I'll think this over once more, but in both designs you still have to write either if-clause or try-catch.. don't see much difference in that.

**Comment by lexxel** [comment]
I can't remember my use case exactly, but you might be right ...

**Comment by ktuukkan** [comment]
Probably related to issue #56, stay tuned for a fix. As the error message says, exception was actually thrown by listener (i.e. your code) while ExceptionListener is for catching IOExceptions occured within the reader. DataNotAvailableException is thrown by individual parsers and thus it is not a problem within the reader. Typically you should just wrap the throwing call in try-catch and try to recover from absence of certain value.

**Comment by WickedShell** [comment]
SentenceListener isn't my code? I've only implemented a PositionListener and the ExceptionListener the rest is all from the library. (My exception handler formats everything differently as well)

**Comment by ktuukkan** [comment]
Ah, yes, when using providers the listener is indeed library code. Sorry, my mistake, was thinking about the usual use case of listeners. Anyways, the issue #56 should resolve this, trying squeeze some time to resolve is soon.

**Comment by WickedShell** [comment]
Thanks will follow closely :)
