### ISSUE TITLE
TalkerId should be a general class, so it can be support unknown type

### ISSUE THREAD

**Issue by chjwch** [ktuukkan/marine-api#37]
The Chinese beidou system's talker id is BD,  there is no BD in the enum TalkerId.

I think if the TalkerId is a generic class can support use-specific talkerId.

**Comment by ktuukkan** [comment]
Thanks for reporting, added BD in TalkerId. Please let me know if you need any other IDs as they are very straight-forward to add. You may use the latest snapshot version before the next release.
