### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by Seraphis** [ktuukkan/marine-api#43]
I get 
ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
at AbstractSentenceListener.java:52

I have pretty similar code to your example at the end of https://github.com/ktuukkan/marine-api/blob/master/src/main/java/net/sf/marineapi/example/SentenceListenerExamples.java file.

**Comment by ktuukkan** [comment]
Hi,
what's the generic type you are using when extending AbstractSentenceListener? It should be one of the actual sentence interfaces (e.g. GGASentence, but any interface GGASentence extends won't work at the moment).

**Comment by Seraphis** [comment]
I'm using GGASentence:
public class GGAListener extends AbstractSentenceListener<GGASentence>

**Comment by ktuukkan** [comment]
I'm unable to reproduce this, could you paste a snippet of your code?

**Comment by Seraphis** [comment]
```java
public class GGAListener extends AbstractSentenceListener<GGASentence> {
		private BluetoothNMAEListener bluetoothNMAEListener;

		public GGAListener(BluetoothNMAEListener bluetoothNMAEListener) {
			super();
			this.bluetoothNMAEListener = bluetoothNMAEListener;
		}
}
```

**Comment by ktuukkan** [comment]
Your code is ok, but I still haven't been able to reproduce this on JDK, maybe Android specific? Which Java version are you using?

**Comment by Seraphis** [comment]
There might be a problem with proguard. Debug apk was working fine. I am still waiting for test results.

**Comment by ktuukkan** [comment]
Closing the issues as related in external tools.
