### ISSUE TITLE
Thread.sleep(50) in AbstractDataReader.java makes files parsing slow

### ISSUE THREAD

**Issue by adrianulbona** [ktuukkan/marine-api#48]
I tested the parser on some large files and it looks like a SentenceReader is quite slow. I suppose that the sleep is required when the UDPDataReader implementation is used, but for the DefaultDataReader it makes sense to call Thread.sleep()?

**Comment by ktuukkan** [comment]
Hi, it's there mainly to prevent reader loop from eating all CPU. I think it would be feasible to make it configurable, if not getting rid of it totally if possible.

**Comment by adrianulbona** [comment]
Thanks for answer. I will think of a solution to make the sleep time configurable and I will send you a pull request. 

By the way, this library is really helpful. :)

**Comment by ktuukkan** [comment]
Thanks, looking forward to it. I'm glad you like it :)

**Comment by adrianulbona** [comment]
Added pull request #49. As everything is running on a thread, the CPU overhead will be reasonable, the OS will handle the CPU load.

**Comment by ktuukkan** [comment]
Added the feature in master now, resolving the issue as I proposed earlier in pull-req #49 (closed).
