### ISSUE TITLE
GGA missing method

### ISSUE THREAD

**Issue by Garatti** [ktuukkan/marine-api#59]
Hello,
Firts of all, Great project!
I was wondering it in the GGA class is there a motivation for the missing setSatelliteCount() method? It is linked to any other information derived from another sentence? I'm using this api in a simuator, and i kinldy ask if it is foreseen in the next future the introduction of such method.
Thank you very much.

**Comment by ktuukkan** [comment]
Hi,
I simply seem to have missed it while adding setters, they were added some time later than getters. Thanks for reporting, I'll add it in the near future :)

**Comment by ktuukkan** [comment]
Added setter in GGA, now available in latest snapshot build.
