### ISSUE TITLE
Add support for TXT sentences

### ISSUE THREAD

**Issue by ktuukkan** [ktuukkan/marine-api#65]
https://www.sparkfun.com/datasheets/GPS/Modules/D2523T%20V1.pdf

https://tnp.uservoice.com/knowledgebase/articles/172139-using-team-tracker-with-nmea-aprs-generic-tracki

**Comment by Emaxoso** [comment]
Yes this could be really usefull

**Comment by ktuukkan** [comment]
TXT support now available in the latest snapshot.
