### ISSUE TITLE
MMSI AIS problem

### ISSUE THREAD

**Issue by erosdet** [ktuukkan/marine-api#73]
In AisMessageFactory i have 

public AISMessage create(AISSentence... sentences) {
AISMessageParser parser = new AISMessageParser();
if (!parsers.containsKey(parser.getMessageType())) {

When create a new AISMessageParser(), the decoder will be instantiated
But when the code go in parser.getMessageType() the decoder can't be == null in the parseAIS() function

MMSI will be 0 for every sentences !!!

**Comment by ktuukkan** [comment]
Thanks for reporting, an obvious mishap while coding.

**Comment by ktuukkan** [comment]
@erosdet, please see de45cb1, I think this resolves it?

**Comment by ktuukkan** [comment]
Resolved by parsing the common fields lazily.
