### ISSUE TITLE
ROTParser does not support setting a negative rate of turn value

### ISSUE THREAD

**Issue by PMudra** [ktuukkan/marine-api#74]
When using `setRateOfTurn` of class `ROTParser` with an negative value an exception is thrown.
This is caused by calling the method `setDegreesValue`.

Rate of turn is not a degree value from 0 to 360 but a speed in degree per minute. The speeds direction can be either clockwise or counterclockwise. The direction is indecated by the sign of the value.

**Comment by ktuukkan** [comment]
Thanks, will be changed to `setDoubleValue` with specific validation if needed.
