### ISSUE TITLE
RPMParser is missing a setRPM method

### ISSUE THREAD

**Issue by PMudra** [ktuukkan/marine-api#75]
The class `RPMParser` does not have a method to set the RPM value. This would be very useful to create RPM sentences.

Reflection can be used as workaround for now by calling `setDoubleValue` with index 2.

**Comment by ktuukkan** [comment]
Thanks for reporting, it must have been simply forgotten.

**Comment by ktuukkan** [comment]
@PMudra, this and #74 now fixed in latest snapshot version.
