### ISSUE TITLE
Maven build fails due to JavaDoc lint errors

### ISSUE THREAD

**Issue by pkoziol** [ktuukkan/marine-api#83]
I'm curious how do you build project. I've run `mvn clean package` which failed, because of JavaDoc lint errors. I had the same problem long time ago, but ignored it, because I've assumed that you didn't support JDK 8. Now I see that you target 1.8, so I'm asking.

Full output: https://gist.github.com/pkoziol/7421ad7ba40fb66c6453431a7a0f4e9e

It's easy to "fix" by adding following configuration to the `pom.xml`:
```
<configuration>
	<additionalparam>-Xdoclint:none</additionalparam>
</configuration>
```

**Comment by ktuukkan** [comment]
Hi! Interesting, I just recently built the project and pushed a new snapshot in the repository, but didn't notice anything like this at the time. Also, the builds have passed in Travis too. Anyways, the errors you get seem legit as some javadoc tags are indeed missing. Will need to add those to fix it, thanks for reporting!

**Comment by ktuukkan** [comment]
Should work on jdk 8 & 9 now. Javadoc generation also now added in CI to better reveal future errors.
