### ISSUE TITLE
Serial Port example needs receive timeout.

### ISSUE THREAD

**Issue by ethanmdavidson** [ktuukkan/marine-api#88]
When attempting to communicate with a gps chip using some code based on the serial port example, I was having trouble connecting to any ports. When scanning ports, every attempt to read from them was throwing "IOException: Underlying stream returned zero bytes.". Based on [this thread](https://community.oracle.com/thread/1145010) I was able to rectify this by adding a timeout to the port before reading it, like so:
```kotlin
sp.setSerialPortParams(9600, SerialPort.DATABITS_8,
		SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
try{
	sp.enableReceiveTimeout(1000);
	sp.enableReceiveThreshold(0);
} catch (e:UnsupportedCommOperationException){
	logger.debug("Unable to set timeout.")
}
```

**Comment by ktuukkan** [comment]
Haven't noticed such behaviour myself, but added the timeout and threshold setting in the example. Thanks!
