### ISSUE TITLE
how to parser type message $PASHR

### ISSUE THREAD

**Issue by DatangYa** [ktuukkan/marine-api#90]
sample NemaStudio $PASHR,042355.7439,0.29,T,+00.02,+00.03,+00.04,0.001,0.002,0.003,1,0*38
help me

**Comment by appurist** [comment]
See [PASHR - RT300 proprietary roll and pitch sentence](http://www.catb.org/gpsd/NMEA.html#_pashr_rt300_proprietary_roll_and_pitch_sentence)

**Comment by DatangYa** [comment]
thank you

**Comment by ktuukkan** [comment]
Hi @DatangYa, need help in understanding the sentence format or for parser implementation? For the latter, please have a look at the instructions given in [SentenceFactory](http://static.javadoc.io/net.sf.marineapi/marineapi/0.10.0/net/sf/marineapi/nmea/parser/SentenceFactory.html).
