### ISSUE TITLE
how to registerParser $PASHR ?

### ISSUE THREAD

**Issue by DatangYa** [ktuukkan/marine-api#92]
registerParser("SHR", SHRParser.class);

**Comment by ktuukkan** [comment]
The `$P` stands for proprietary sentence, so you should use both manufacturer ID and sentence type when registering, i.e .`registerParser("ASHR", ASHRParser.class);`

**Comment by DatangYa** [comment]
thank you master

**Comment by DatangYa** [comment]
registerParser("SHR", SHRParser.class);  
ex : $PVTM0 ? How to registerParser ?

**Comment by ktuukkan** [comment]
The same pattern, `registerParser("VTM0", VTM0Parser.class);`
