### ISSUE TITLE
$PRHO,xxx,DFSTD,0,1,S,243.000,25.0,95.0,30.0,60.0,63.0,31.5,37.0*36

### ISSUE THREAD

**Issue by rizkypras** [ktuukkan/marine-api#93]
help me,  how to parser example ?

**Comment by ktuukkan** [comment]
Hi, see [SentenceFactory](http://static.javadoc.io/net.sf.marineapi/marineapi/0.10.0/net/sf/marineapi/nmea/parser/SentenceFactory.html) for instructions on custom parsers and then see your device's documentation for the proprietary sentence format.
