### ISSUE TITLE
SentenceId Javadoc Mentions NMEA 0831 Instead of 0183 (Trivial)

### ISSUE THREAD

**Issue by mversaggi** [ktuukkan/marine-api#97]
Simple spelling error in SentenceId class javadoc, just wanted to bring it to attention:

https://ktuukkan.github.io/marine-api/0.10.0/javadoc/net/sf/marineapi/nmea/sentence/SentenceId.html

**Comment by ktuukkan** [comment]
Ok, thanks for pointing out! :)
